--
-- PostgreSQL database dump
--

-- Dumped from database version 15.2 (Debian 15.2-1.pgdg110+1)
-- Dumped by pg_dump version 15.2

-- Started on 2023-02-21 02:22:32

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

-- CREATE SCHEMA public;
DO $$
BEGIN
    IF NOT EXISTS (SELECT schema_name
                   FROM information_schema.schemata
                   WHERE schema_name = 'public') THEN
        EXECUTE 'CREATE SCHEMA public';
    END IF;
END
$$;



ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 3327 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 16390)
-- Name: punto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.punto (
    dbid bigint NOT NULL,
    alcaldia character varying(256),
    colonia character varying(256),
    fecha_instalacion date,
    id character varying(256),
    latitud double precision,
    longitud double precision,
    programa character varying(256)
);


ALTER TABLE public.punto OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 16389)
-- Name: punto_dbid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.punto ALTER COLUMN dbid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.punto_dbid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3321 (class 0 OID 16390)
-- Dependencies: 215
-- Data for Name: punto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.punto (dbid, alcaldia, colonia, fecha_instalacion, id, latitud, longitud, programa) FROM stdin;
\.


--
-- TOC entry 3328 (class 0 OID 0)
-- Dependencies: 214
-- Name: punto_dbid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.punto_dbid_seq', 30314, true);


--
-- TOC entry 3177 (class 2606 OID 16396)
-- Name: punto punto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.punto
    ADD CONSTRAINT punto_pkey PRIMARY KEY (dbid);


-- Completed on 2023-02-21 02:22:32

--
-- PostgreSQL database dump complete
--

