spring:
  main:
    banner-mode: off
 
  output:
    ansi:
      enabled: ALWAYS

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl        
    
  datasource:   
#    url: jdbc:postgresql://localhost:5432/PUNTOSW
    url: jdbc:mariadb://127.0.0.1:3306/PUNTOSW
    username: db_usuario
    password: asdf1234    
  
    
server:  
  port: 80
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 512
  http2:
    enabled: true    
      
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://10.50.47.190:8761/eureka/
      